In [1]:
import pandas as pd
import sklearn
import numpy as np

In [2]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [4]:
data = pd.read_excel('/content/PCOS_data_without_infertility.xlsx',sheet_name = 'Full_new')

In [5]:
data.head()

Sl. No  Patient File No.  PCOS (Y/N)   Age (yrs)  Weight (Kg)  Height(Cm)   \
0     1.0               1.0         0.0        28.0         44.6        152.0   
1     2.0               2.0         0.0        36.0         65.0        161.5   
2     3.0               3.0         1.0        33.0         68.8        165.0   
3     4.0               4.0         0.0        37.0         65.0        148.0   
4     5.0               5.0         0.0        25.0         52.0        161.0   

         BMI  Blood Group  Pulse rate(bpm)   RR (breaths/min)  ...  \
0  19.300000         15.0              78.0              22.0  ...   
1  24.921163         15.0              74.0              20.0  ...   
2  25.270891         11.0              72.0              18.0  ...   
3  29.674945         13.0              72.0              20.0  ...   
4  20.060954         11.0              72.0              18.0  ...   

   Fast food (Y/N)  Reg.Exercise(Y/N)  BP _Systolic (mmHg)  \
0              1.0                0.0                110.0   
1              0.0                0.0                120.0   
2              1.0                0.0                120.0   
3              0.0                0.0                120.0   
4              0.0                0.0                120.0   

   BP _Diastolic (mmHg)  Follicle No. (L)  Follicle No. (R)  \
0                  80.0               3.0               3.0   
1                  70.0               3.0               5.0   
2                  80.0              13.0              15.0   
3                  70.0               2.0               2.0   
4                  80.0               3.0               4.0   

   Avg. F size (L) (mm) Avg. F size (R) (mm)  Endometrium (mm)  Unnamed: 44  
0                  18.0                 18.0               8.5          NaN  
1                  15.0                 14.0               3.7          NaN  
2                  18.0                 20.0              10.0          NaN  
3                  15.0                 14.0               7.5          NaN  
4                  16.0                 14.0               7.0          NaN  

[5 rows x 45 columns]

In [6]:
data.columns

Index(['Sl. No', 'Patient File No.', 'PCOS (Y/N)', ' Age (yrs)', 'Weight (Kg)',
       'Height(Cm) ', 'BMI', 'Blood Group', 'Pulse rate(bpm) ',
       'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)', 'Cycle length(days)',
       'Marraige Status (Yrs)', 'Pregnant(Y/N)', 'No. of aborptions',
       '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)', 'FSH(mIU/mL)',
       'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio',
       'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)',
       'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)',
       'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)',
       'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)',
       'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)',
       'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)',
       'Unnamed: 44'],
      dtype='object')

In [7]:
data = data.fillna(0)

In [8]:
y = data['PCOS (Y/N)']
X = data[[' Age (yrs)', 'Weight (Kg)','Height(Cm) ', 'BMI','Pulse rate(bpm) ', 'RR (breaths/min)','Cycle length(days)',
          'Pregnant(Y/N)','Weight gain(Y/N)', 'hair growth(Y/N)',
       'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)',
       'Fast food (Y/N)', 'Reg.Exercise(Y/N)']]

In [9]:
X.head()

Age (yrs)  Weight (Kg)  Height(Cm)         BMI  Pulse rate(bpm)   \
0        28.0         44.6        152.0  19.300000              78.0   
1        36.0         65.0        161.5  24.921163              74.0   
2        33.0         68.8        165.0  25.270891              72.0   
3        37.0         65.0        148.0  29.674945              72.0   
4        25.0         52.0        161.0  20.060954              72.0   

   RR (breaths/min)  Cycle length(days)  Pregnant(Y/N)  Weight gain(Y/N)  \
0              22.0                 5.0            0.0               0.0   
1              20.0                 5.0            1.0               0.0   
2              18.0                 5.0            1.0               0.0   
3              20.0                 5.0            0.0               0.0   
4              18.0                 5.0            1.0               0.0   

   hair growth(Y/N)  Skin darkening (Y/N)  Hair loss(Y/N)  Pimples(Y/N)  \
0               0.0                   0.0             0.0           0.0   
1               0.0                   0.0             0.0           0.0   
2               0.0                   0.0             1.0           1.0   
3               0.0                   0.0             0.0           0.0   
4               0.0                   0.0             1.0           0.0   

   Fast food (Y/N)  Reg.Exercise(Y/N)  
0              1.0                0.0  
1              0.0                0.0  
2              1.0                0.0  
3              0.0                0.0  
4              0.0                0.0

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0    Age (yrs)            541 non-null    float64
 1   Weight (Kg)           541 non-null    float64
 2   Height(Cm)            541 non-null    float64
 3   BMI                   541 non-null    float64
 4   Pulse rate(bpm)       541 non-null    float64
 5   RR (breaths/min)      541 non-null    float64
 6   Cycle length(days)    541 non-null    float64
 7   Pregnant(Y/N)         541 non-null    float64
 8   Weight gain(Y/N)      541 non-null    float64
 9   hair growth(Y/N)      541 non-null    float64
 10  Skin darkening (Y/N)  541 non-null    float64
 11  Hair loss(Y/N)        541 non-null    float64
 12  Pimples(Y/N)          541 non-null    float64
 13  Fast food (Y/N)       541 non-null    float64
 14  Reg.Exercise(Y/N)     541 non-null    float64
dtypes: float64(15)
memory u

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y)

In [12]:
model1 = DecisionTreeClassifier()
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test)
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy =  0.7352941176470589
Confusion matrix:
 [[77 17]
 [19 23]]


In [13]:
model2 = RandomForestClassifier()
model2.fit(x_train,y_train)
y_pred = model2.predict(x_test)
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy =  0.8455882352941176
Confusion matrix:
 [[89  5]
 [16 26]]


In [14]:
model3 = KNeighborsClassifier()
model3.fit(x_train,y_train)
y_pred = model3.predict(x_test)
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy =  0.6764705882352942
Confusion matrix:
 [[79 15]
 [29 13]]


In [15]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [16]:
from joblib import dump, load
dump(model, 'RandomForestModel.joblib')

['RandomForestModel.joblib']

In [17]:
y = data['PCOS (Y/N)']
X = data[[' Age (yrs)', 'Weight (Kg)',
       'Height(Cm) ', 'BMI', 'Pulse rate(bpm) ',
       'RR (breaths/min)', 'Hb(g/dl)', 'Cycle length(days)', 'Pregnant(Y/N)',
       '  I   beta-HCG(mIU/mL)','FSH(mIU/mL)',
       'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio',
       'TSH (mIU/L)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)',
       'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)',
       'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)',
       'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)',
       'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)',
       'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)']]

In [18]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0    Age (yrs)              541 non-null    float64
 1   Weight (Kg)             541 non-null    float64
 2   Height(Cm)              541 non-null    float64
 3   BMI                     541 non-null    float64
 4   Pulse rate(bpm)         541 non-null    float64
 5   RR (breaths/min)        541 non-null    float64
 6   Hb(g/dl)                541 non-null    float64
 7   Cycle length(days)      541 non-null    float64
 8   Pregnant(Y/N)           541 non-null    float64
 9     I   beta-HCG(mIU/mL)  541 non-null    float64
 10  FSH(mIU/mL)             541 non-null    float64
 11  LH(mIU/mL)              541 non-null    float64
 12  FSH/LH                  541 non-null    float64
 13  Hip(inch)               541 non-null    float64
 14  Waist(inch)             541 non-null    fl

In [19]:
x_train,x_test,y_train,y_test = train_test_split(X,y)

In [20]:
model1 = DecisionTreeClassifier()
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test)
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy =  0.7647058823529411
Confusion matrix:
 [[74 17]
 [15 30]]


In [21]:
model2 = RandomForestClassifier()
model2.fit(x_train,y_train)
y_pred = model2.predict(x_test)
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy =  0.9191176470588235
Confusion matrix:
 [[89  2]
 [ 9 36]]


In [22]:
model3 = KNeighborsClassifier()
model3.fit(x_train,y_train)
y_pred = model3.predict(x_test)
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy =  0.6764705882352942
Confusion matrix:
 [[80 11]
 [33 12]]


In [23]:
model1 = RandomForestClassifier()
model1.fit(x_train,y_train)

RandomForestClassifier()

In [24]:
from joblib import dump, load
dump(model1, 'RandomForestModel1.joblib')

['RandomForestModel1.joblib']